# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f39b397c515b556d2c675da5917acb0845073cd59ae38e231b877e5a147ce5673343e5650c406bac84ad751e2b19551ada6e803750f76f6015370be56ce796

test:
  secret_key_base: ee8c6fc944d4b239ee4f7bbad9d612ad31a2757ea652e8d59312929fb76ddf544c553ed346a300938462460f468effeb70f3e2e645adc7cfca4c95b350ce5343

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
